moveit_simple_controller_manager:
  controller_names:
    - upper_body_controller
    - head_controller

  upper_body_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
      - joint9
      - joint10
      - joint11
      - joint12
      - joint13
      - joint14

  head_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - Revolute 15